### ISSUE TITLE
Integration with fancontrol-gui/kcm ?

### ISSUE THREAD

**Issue by unfa** [Eraden/amdgpud#30]
fancontrol-gui is a very nice visual front-end to fancontrol.
fancontrol-kcm integrates fancontrol-gui with KDE Control Center which is even better, as it allows the user to have all the settings integrated in one place.

The problem is - fancontrol doens't allow specifying a _curve_. Only a _linear function_.

![image](https://user-images.githubusercontent.com/491704/144678292-8e78b9f5-b3e4-4cc9-a4b8-50b7cf2c9ac8.png)

amdfand fills that gap, but I wasn't able to find a visual tool for it.
Maybe some collaboration between the projects could be done to integrate all the best features?

**Comment by Eraden** [comment]
To be honest I'm planning to create GUI and even started investigating [egui](https://github.com/emilk/egui) since it has potting. Second step is checking if [druid](https://github.com/linebender/druid) could be better.

But I'll check what I can do for [fancontrol-gui](https://github.com/Maldela/Fancontrol-GUI) and fancontrol-kcm

**Comment by olielvewen** [comment]
```
Maybe some collaboration between the projects could be done to integrate all the best features?
```

@unfa 

Excellent idea. The interface is rather pleasant and functional. In addition, it will avoid too much work to Eraden.

This solution will quickly provide an interface that can serve as a starting point for Eraden if he still wants to create his own interface in Rust.

**Comment by Eraden** [comment]
@olielvewen  @unfa 

Please check this: https://github.com/Eraden/amdgpud/tree/gui-app/amdguid

Is this temporarily ok with you?

**Comment by olielvewen** [comment]
@Eraden 

Great. What is the process to test all this ? Thanks

**Comment by Eraden** [comment]
@olielvewen

# Ubuntu binaries

https://github.com/Eraden/amdgpud/actions/runs/1760759493

# Arch Linux binaries

https://static.ita-prog.pl/archlinux-amdgui.zip

# From source

* Install rustup from here: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
* Add nightly as a default

```
rustup default nightly
```

* Download code

```
git clone https://github.com/Eraden/amdgpud.git
git checkout gui-app
```

* Build binaries

```
cargo build --release
```

# Running

Then:

* Unzip binaries
* Stop amdfand is it's working
* Start amdfand manually with root privilages

```
sudo amdfand service
```


* Start gui helper with root privilages

```
sudo amdgui-helper
```

* Unzip glium (Xorg) or Wayland gui version, to check which you need please run this script:

```
loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'
```

If you got `wayland` you should use wayland, otherwise you need glium

* Run gui app *without* root. For Wayland root is not even possible

```
amdguid
```

There's `/tmp/amdgui-helper.sock` file which is communication channel between helper and local host application so you can implement you in other way.

# HELP, I'M LOST

* You can reach me here: https://www.reddit.com/r/amdgpud/ or as u/Tsumanu
* Discord: https://discord.gg/G66sF8jw

**Comment by olielvewen** [comment]
Hi @Eraden ,

I come back on this computer today.

Firstly, I'm running on Manjaro Cinnamon last kernel with a graphic card Gigabyte RX 5500 XT 8 Go and Xorg.

I run into an issue directly. I can't run amdfand in a terminal opened in the archlinux folder (and unzip gluim)

```
sudo ./amdfand service
sudo: ./amdfand : commande introuvable
```

After I have tried to run amdfand installed on my computer without anysuccess (he was not installed on this computer, In fact, I have already try to use amdfan in live sessions)

```
sudo amdfand
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', /home/eraden/code/eraden/amdgpu/amdgpud/amdgpu/src/utils.rs:95:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

THis command doesn't work (no output)

```
loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'
```

I 'm trying to catch you on Discord, nice to have an channel. ^ \_ ^

**Comment by Eraden** [comment]
I think there's something really wrong with upx compression here

Please check those binaries:

https://static-ita-prog.pl/archlinux-amdgui.zip

Or compile `release` without `upx`
