### ISSUE TITLE
code: 13, kind: PermissionDenied, message: "Permission denied"

### ISSUE THREAD

**Issue by Pakrohk** [Eraden/amdgpud#52]
There was problem accessing hwmon4 and hwmon3, how can I solve this problem?

`sudo amdfand set-automatic`

```log
INFO  amdfand > Config { path: "/etc/amdfand/config.toml", temp_input: Some(TempInput(1)), log_level: Error, cards: None, speed_matrix: [MatrixPoint { temp: 4.0, speed: 4.0 }, MatrixPoint { temp: 30.0, speed: 33.0 }, MatrixPoint { temp: 45.0, speed: 50.0 }, MatrixPoint { temp: 60.0, speed: 66.0 }, MatrixPoint { temp: 65.0, speed: 69.0 }, MatrixPoint { temp: 70.0, speed: 75.0 }, MatrixPoint { temp: 75.0, speed: 89.0 }, MatrixPoint { temp: 80.0, speed: 100.0 }] }
 ERROR amdfand::change_mode > Fan(AutomaticSpeedFailed(Write { io: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }, path: "/sys/class/drm/card1/device/hwmon/hwmon4/pwm1_enable" }))
 ERROR amdfand::change_mode > Fan(AutomaticSpeedFailed(Write { io: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }, path: "/sys/class/drm/card0/device/hwmon/hwmon3/pwm1_enable" }))
 ```

**Comment by Eraden** [comment]
You must likely needs to change boot flags for AMD cards. Default does not allow changing card settings via sysfs.

From archlinux Wiki:

It is required to unlock access to adjust clocks and voltages in sysfs by appending the Kernel parameter amdgpu.ppfeaturemask=0xffffffff.

Not all bits are defined, and new features may be added over time. Setting all 32 bits may enable unstable features that cause problems such as screen flicker or broken resume from suspend. It should be sufficient to set the PP_OVERDRIVE_MASK bit, 0x4000, in combination with the default ppfeaturemask. To compute a reasonable parameter for your system, execute:

```
$ printf 'amdgpu.ppfeaturemask=0x%x\n' "$(($(cat /sys/module/amdgpu/parameters/ppfeaturemask) | 0x4000))"
```

https://wiki.archlinux.org/title/AMDGPU#Features

Then reboot since this has effect on sysfs

After this you are ready to go
